# Generated by Django 3.2.16 on 2022-11-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Extracts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bank", models.CharField(max_length=256, verbose_name="Bank")),
                ("document_section", models.CharField(max_length=256, verbose_name="Document section")),
                ("number", models.CharField(max_length=50, verbose_name="Number")),
                ("date", models.DateField(verbose_name="Date")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="The amount")),
                ("date_written_off", models.DateField(null=True, verbose_name="Date written off")),
                ("date_received", models.DateField(null=True, verbose_name="Date received")),
                ("payer", models.CharField(max_length=256, verbose_name="Payer")),
                ("payer_payment_account", models.CharField(max_length=50, verbose_name="Payer payment account")),
                ("payer_of_inn", models.CharField(max_length=50, verbose_name="Payer of INN")),
                ("recipient", models.CharField(max_length=100, verbose_name="Recipient")),
                (
                    "recipient_payment_account",
                    models.CharField(max_length=100, verbose_name="Recipient payment account"),
                ),
                ("recipient_of_inn", models.CharField(max_length=50, verbose_name="Payer of INN")),
                ("purpose_of_payment", models.CharField(max_length=256, verbose_name="Purpose of payment")),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Extracts",
                "verbose_name_plural": "Extracts",
                "ordering": ("-deleted", "-date_written_off", "-date_received"),
            },
        ),
    ]
