# Generated by Django 3.2.16 on 2022-11-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extractapp", "0002_extractsoddrecipient"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExtractsOddRecipient",
            new_name="ExtractsOddExpenditure",
        ),
        migrations.AlterModelOptions(
            name="extractsoddexpenditure",
            options={"verbose_name": "Extracts Odd Expenditure", "verbose_name_plural": "Extracts Odd Expenditure"},
        ),
    ]
