# Generated by Django 3.2.16 on 2022-11-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractapp", "0004_extractsoddincom"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracts",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
