# Generated by Django 3.2.16 on 2022-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractapp", "0005_extracts_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracts",
            name="tranzaction",
            field=models.BooleanField(default=False),
        ),
    ]
