# Generated by Django 3.2.16 on 2022-11-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extractapp", "0006_extracts_tranzaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extracts",
            old_name="tranzaction",
            new_name="transaction",
        ),
    ]
