# Generated by Django 3.2.16 on 2022-11-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extractapp", "0007_rename_tranzaction_extracts_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extracts",
            options={
                "ordering": ("transaction", "-date_written_off", "-date_received"),
                "verbose_name": "Extracts",
                "verbose_name_plural": "Extracts",
            },
        ),
    ]
