# Generated by Django 3.2.16 on 2022-12-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractapp", "0008_alter_extracts_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extracts",
            options={
                "ordering": ("transaction", "-date"),
                "verbose_name": "Extracts",
                "verbose_name_plural": "Extracts",
            },
        ),
        migrations.RemoveField(
            model_name="extracts",
            name="date_received",
        ),
        migrations.RemoveField(
            model_name="extracts",
            name="date_written_off",
        ),
        migrations.AddField(
            model_name="extracts",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
