# Generated by Django 3.2.16 on 2022-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractsOddRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Extracts Odd Recipient",
                "verbose_name_plural": "Extracts Odd Recipient",
            },
        ),
    ]
