# Generated by Django 3.2.16 on 2022-12-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settingapp", "0002_menu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ("-menu",), "verbose_name": "Menu", "verbose_name_plural": "Menu"},
        ),
    ]
